Switching To Debian Based Installation System (PAL Mini)
DreamVu/3D-Object-Detection-Tracking pull request #3
Opened 2022-08-08 14:50 UTC by debashish05

Ported PAL-USB installation to Debian from a script-based system. Debian source files are maintained at https://github.com/DreamVu/debian_installations_files/tree/3d-object-detection-tracking and https://github.com/DreamVu/Firmware/tree/I006_Tracking_JPP/deb.

2022-08-09 04:42 UTC, romil611 requested changes
The pal-mini's libPAL.so seems to have changed. Please mention the changes done here.

2022-08-09 07:58 UTC, debashish05 commented
I didn't know the new way of creating lib files, but that lib file need change.

2022-08-19 06:47 UTC, romil611 commented on code_samples/001_people_tracking.cpp
> +    printf("Update Done\n");
Should this be here?

2022-08-19 06:51 UTC, piyush-312 commented on code_samples/001_people_tracking.cpp
> +    printf("Update Done\n");
just a temp update..ignore will anyway create fresh PR for both branches after testing gets completed.

2022-08-22 13:45 UTC, closed without merging